build:
command: CI= npm run build
commandOrigin: config
environment:
  - NODE_VERSION
  - NPM_VERSION
publish: /opt/build/repo/public
publishOrigin: config
plugins:
  - inputs: {}
    origin: ui
    package: '@netlify/plugin-gatsby'